# YML
services:
  box3:
    image: alpine
    container_name: Box3
    command: sleep 3600
  box4:
    image: alpine
    command: sleep 3600
    deploy:
      replicas: 10
  db:
    image: mysql
    container_name: MySQLDB
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: testdb
    ports:
      - "3311:3306"
      - "3312:3306"
    volumes:
      - ./data:/var/lib/mysql
      - mysqlsuperdb:/var/lib/mysql

volumes:
  mysqlsuperdb:
    driver: local


# docker compose up -d
# docker compose ps
# docker compose down