name: Docker build

on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Clonar repositorio
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Construir image
          run: docker build -t victor-crea/node-test:latest .

        - name: Publicar en Docker Hub
          run: docker push victor-crea/node-test:latest