name: Docker build

on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Clonar repositorio
          uses: actions/checkout@v4

        - name: Construir image
          run: docker build -t node-test:1 .